### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by tasseff** [lanl-ansi/PowerWaterModels.jl#2]

**Comment by tasseff** [comment]
@ccoffrin, feel free to review and post issues regarding 3825c42, which I anticipate will be our v0.0.1 release. Just waiting on the new release of PowerModelsDistribution with multinetwork problems before initiating.

**Comment by ccoffrin** [comment]
Reame is fine by me.  I have a slight preference to move the boiler plate legal stuff like, "Work at Los Alamos National Laboratory is conducted under the auspices of the National Nuclear Security Administration of the U.S. Department of Energy under Contract No. 89233218CNA000001."  Into the license doc rather than the readme.

**Comment by tasseff** [comment]
v0.0.1 @JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.0.1 @JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.1.0 @JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.2.0 @JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.3.0 @JuliaRegistrator register()

**Comment by tasseff** [comment]
v0.3.0 @JuliaRegistrator register()
